### PR TITLE
Variables extensions

### LINKED ISSUE #214: Response Variables property is not very convenient
The response `Variables `property is a string and this is not very convenient: the proof is the addition of a `getVariablesAsMap ` method in the java client.

The solution would be to add the same kind of facilities in the C# client: `GetVariablesAsMap `and `GetVariablesAsType `(names are the same as the java ones) that return respectively an `IReadOnlyDictionary<string, object>` and `T`.

Remaining questions are:

- the choice of a JSON serializer i.e. Newtonsoft Json.NET vs MS System.Text.Json as we would add a new dependency to the client. For testing you use the 1st one.
- and this dependency would be exposed because in the `IReadOnlyDictionary<string, object>`, the value could be a `JObject`. 

I can make a PR if you agree.

Thank you

### PR DESCRIPTION
**Pull request by xlegalles**
Variables extensions similar to the ones present in the Java client.
close #214

### CODE REVIEW

**Comment by Zelldon** [comment]
Hey @xlegalles 

thanks for your contribution sorry that it took me so long to send a response to this. 

I'm a bit unsure with these additions, since we introduce here a new dependency which might be problematic for some users if they don't want to use `Newtonsoft`.

Actually we removed the dependency a year ago https://github.com/zeebe-io/zeebe-client-csharp/issues/36 I would rather not to introduce it again. Why do you think this needs to be part of the lib and can't stay in your application code?

Greets
Chris

**Review by Zelldon — COMMENTED** [review]
Hey @xlegalles

thanks for your contribution sorry that it took me so long to send a response to this.

I'm a bit unsure with these additions, since we introduce here a new dependency which might be problematic for some users if they don't want to use Newtonsoft.

Actually we removed the dependency a year ago #36 I would rather not to introduce it again. Why do you think this needs to be part of the lib and can't stay in your application code?

Greets
Chris

**Comment by xlegalles** [comment]
I totally understand this question of dependency. So you can deny my PR, no pb.

**Comment by Zelldon** [comment]
Thanks @xlegalles

**Pull request closed without merging**
